import { RoutePathDefinition } from 'src/lib/routes/RoutePathDefinition';

export const processRoutes: RoutePathDefinition[] = [
  {
    title: 'Partner Admin',
    path: '/',
    nav: true,
    startIcon: 'chevronLeftIcon',
    endIcon: 'chevronRightIcon',
  },
  {
    title: 'General Admin',
    path: '/',
    nav: true,
    startIcon: 'chevronLeftIcon',
    endIcon: 'chevronRightIcon',
    children: [
      {
        title: 'Setups',
        path: '/',
        nav: true,
        startIcon: 'chevronLeftIcon',
        endIcon: 'chevronRightIcon',
      },
      {
        title: 'Data Management',
        path: '/',
        nav: true,
        startIcon: 'chevronLeftIcon',
        endIcon: 'chevronRightIcon',
        children: [
          {
            title: 'Remove Payroll Data',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Remove Reporting Essentials Data',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Check Employee ID Issues',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Check Dependent Duplicate Issues',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Recalculate Affordability by Current Year',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Edit Brands',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'View Process Queue',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Measurement Calculations',
            path: '/',
            nav: true,
            startIcon: 'chevronLeftIcon',
            endIcon: 'chevronRightIcon',
            children: [
              {
                title: 'Schedule Measurement',
                path: '/',
                nav: true,
                startIcon: 'placeholder',
                endIcon: 'placeholder',
              },
            ],
          },
          {
            title: 'Client XML Download',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Client NJ XML Download',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Client Washington DC XML Download',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Client Rhode Island XML Download',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Client California XML Download',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
          {
            title: 'Historical Print Queue',
            path: '/',
            nav: true,
            startIcon: 'placeholder',
            endIcon: 'placeholder',
          },
        ],
      },
      {
        title: 'Reports',
        path: '/',
        nav: true,
        startIcon: 'chevronLeftIcon',
        endIcon: 'chevronRightIcon',
      },
      {
        title: 'Imports',
        path: '/',
        nav: true,
        startIcon: 'chevronLeftIcon',
        endIcon: 'chevronRightIcon',
      },
      {
        title: 'Site Alerts',
        path: '/',
        nav: true,
        startIcon: 'chevronLeftIcon',
        endIcon: 'chevronRightIcon',
      },
      {
        title: 'Misc.',
        path: '/',
        nav: true,
        startIcon: 'chevronLeftIcon',
        endIcon: 'chevronRightIcon',
      },
      {
        title: 'Billing',
        path: '/',
        nav: true,
        startIcon: 'chevronLeftIcon',
        endIcon: 'chevronRightIcon',
      },
    ],
  },
];
